In [1]:
v = [1, 2, 3, 4, 5]
sm = [2 * i for i in v]
sm

[2, 4, 6, 8, 10]

In [2]:
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [3]:
import numpy as np

a = np.array(v)
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
2 * a

array([ 2,  4,  6,  8, 10])

In [6]:
0.5 * a + 2

array([2.5, 3. , 3.5, 4. , 4.5])

In [8]:
a = np.arange(12).reshape((4, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
2 * a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [10]:
a ** 2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [11]:
a.mean()

5.5

In [12]:
np.mean(a)

5.5

In [13]:
a.mean(axis = 0)

array([4.5, 5.5, 6.5])

In [15]:
np.mean(a, axis = 1)

array([ 1.,  4.,  7., 10.])